namespace VehiclesForSale.Data.Models.Vehicle.Enums
{
    public enum SafetyExtra
    {
        ABS = 1,
        ESP = 2,
        Airbag = 3,
        Alarm = 4,
        Immobilizer = 5,
        CentralLocking = 6,
        ChildLock = 7,
        TractionControl = 8,
        XenonHeadlights = 9,
        LEDHeadlights = 10,
        FogLights = 11,
        ParkingSensors = 12,
        RearViewCamera = 13,
        RainSensor = 14,
        ISOFix = 15,
        EmergencyBrake = 16,
        LaneAssist = 17,
        BlindSpotMonitoring = 18,
        AdaptiveCruiseControl = 19,
        CollisionAvoidanceSystem = 20,
        TirePressureMonitoring = 21,
        NightVision = 22,
        DriverMonitoring = 23,
        PassengerMonitoring = 24,
        RearCrossTrafficAlert = 25,
        ForwardCollisionWarning = 26,
        AutomaticEmergencyBraking = 27,
        PedestrianDetection = 28,
        TrafficSignRecognition = 29,
        AdaptiveHeadlights = 30,
        AdaptiveHighBeam = 31,
        AdaptiveBrakeLights = 32,
        AdaptiveSuspension = 33,
        AdaptiveSteering = 34,
        AdaptiveBraking = 35,
        AdaptiveSpeedLimiter = 36,
        AdaptiveThrottle = 37,
        AdaptiveExhaust = 38,
        AdaptiveEngine = 39,
        AdaptiveTransmission = 40,
        AdaptiveDifferential = 41,
        AdaptiveTractionControl = 42,
        AdaptiveStabilityControl = 43,
        AdaptiveAllWheelDrive = 44,
        AdaptiveFourWheelDrive = 45,
        AdaptiveRearWheelDrive = 46,
        AdaptiveFrontWheelDrive = 47,
        AdaptiveFrontWheelSteering = 48,
        AdaptiveRearWheelSteering = 49,
        AdaptiveAllWheelSteering = 50,
        AdaptiveFourWheelSteering = 51
    }
}
